// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2NMUDJysNDCh8PyQHYeQBth9pyRm6AsI',
    appId: '1:586618493457:web:d729722464aa8d6a0c6fb0',
    messagingSenderId: '586618493457',
    projectId: 'quizapp-3bf94',
    authDomain: 'quizapp-3bf94.firebaseapp.com',
    storageBucket: 'quizapp-3bf94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdRRc_MO5eM7k21h88CMRQL0Rbk_T2Ng',
    appId: '1:586618493457:android:439ba786f619535a0c6fb0',
    messagingSenderId: '586618493457',
    projectId: 'quizapp-3bf94',
    storageBucket: 'quizapp-3bf94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRLiyWcPrCxiuk5E9K1LtM2hXDkjTe0Qo',
    appId: '1:586618493457:ios:7187421d06791b7d0c6fb0',
    messagingSenderId: '586618493457',
    projectId: 'quizapp-3bf94',
    storageBucket: 'quizapp-3bf94.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRLiyWcPrCxiuk5E9K1LtM2hXDkjTe0Qo',
    appId: '1:586618493457:ios:7187421d06791b7d0c6fb0',
    messagingSenderId: '586618493457',
    projectId: 'quizapp-3bf94',
    storageBucket: 'quizapp-3bf94.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2NMUDJysNDCh8PyQHYeQBth9pyRm6AsI',
    appId: '1:586618493457:web:e68f4e5207888f060c6fb0',
    messagingSenderId: '586618493457',
    projectId: 'quizapp-3bf94',
    authDomain: 'quizapp-3bf94.firebaseapp.com',
    storageBucket: 'quizapp-3bf94.appspot.com',
  );
}